# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: curency.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='curency.proto',
  package='curency',
  syntax='proto2',
  serialized_pb=_b('\n\rcurency.proto\x12\x07\x63urency\"\x1f\n\rDollarCurency\x12\x0e\n\x06rubles\x18\x01 \x02(\x01\"\x0c\n\nEmptyInput2T\n\x14\x44ollarCurencyService\x12<\n\rGetDollarRate\x12\x13.curency.EmptyInput\x1a\x16.curency.DollarCurency')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DOLLARCURENCY = _descriptor.Descriptor(
  name='DollarCurency',
  full_name='curency.DollarCurency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rubles', full_name='curency.DollarCurency.rubles', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=57,
)


_EMPTYINPUT = _descriptor.Descriptor(
  name='EmptyInput',
  full_name='curency.EmptyInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['DollarCurency'] = _DOLLARCURENCY
DESCRIPTOR.message_types_by_name['EmptyInput'] = _EMPTYINPUT

DollarCurency = _reflection.GeneratedProtocolMessageType('DollarCurency', (_message.Message,), dict(
  DESCRIPTOR = _DOLLARCURENCY,
  __module__ = 'curency_pb2'
  # @@protoc_insertion_point(class_scope:curency.DollarCurency)
  ))
_sym_db.RegisterMessage(DollarCurency)

EmptyInput = _reflection.GeneratedProtocolMessageType('EmptyInput', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYINPUT,
  __module__ = 'curency_pb2'
  # @@protoc_insertion_point(class_scope:curency.EmptyInput)
  ))
_sym_db.RegisterMessage(EmptyInput)


# @@protoc_insertion_point(module_scope)
